version: '3.7'

services:
  database:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: luminate
      POSTGRES_USER: user
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.4
    restart: unless-stopped
    volumes:
      - redis-storage:/data
    ports:
      - 6379:6379

volumes:
  database-storage:
  redis-storage:
