POST http://localhost:4000/webhook/omise
Content-Type: application/json

{
  "object": "event",
  "data": {
    "object": "charge",
    "id": "chrg_test_5wxy7osn2d08moelywp",
    "metadata": {
      "createdBy": "LUMINATE"
    }
  }
} 
