-- AlterTable
ALTER TABLE "live_course" ALTER COLUMN "fundamentalsCourseIds" SET DATA TYPE TEXT[],
ALTER COLUMN "exerciseIds" SET DATA TYPE TEXT[],
ALTER COLUMN "examTutorialIds" SET DATA TYPE TEXT[],
ALTER COLUMN "examIds" SET DATA TYPE TEXT[],
ALTER COLUMN "mockExamIds" SET DATA TYPE TEXT[];
